module.exports = {
  ERRORS: {
    // USER ERRORS
    tokenInvalid: "Unauthorized access: Token not found",
    userNotFound: "Unauthorized access: User does not exist",
    unAuthorized: "Unauthorized access",
    emailInvalid: "Invalid Email",
  },
  TEXTS: {
    userCreated: "User created successfully",
    userLogin: "User login successfully",
    userLoggedOut: "User logout successfully",
    userUpdated: "User updated successfully",
    passwordUpdated: "Password updated successfully",
  },
  ROLES: {
    MEMBER: "member",
    ADMIN: "admin",
    CLIENT: "client",
    COACH: "coach",
    COMPANY: "company",
    ACCESS_GROUP: "accessGroup",
    REPORTING: "reporting",
  },
  STATUS: {
    ACTIVE: "active",
    PENDING: "pending",
    ACCEPTED: "accepted",
    REJECTED: "rejected",
    INPROGRESS: "inprogress",

    INACTIVE: "inactive",
    UNAPPROVED: "unapproved",
    APPROVED: "approved",
    VERIFIED: "verified",
    EXPIRED: "expired",
    USED: "used",
    COMPLETED: "completed",
    INCOMPLETE: "incomplete",
    VERFIFIED: "verified",
    CANCEL: "cancel",
    ENDED: "ended",
    CLOSED: "closed",
    Open: "Open",
  },
  STATUS_CODE: {
    NOT_FOUND: 404,
    EXISTS: 400,
    INTERNAL_SERVER_ERROR: 500,
    SUCCESS: 200,
    CREATED: 201,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
  },
};
